/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DirIdRouteRouteImport } from './routes/dir.$id/route'
import { Route as DirIdFileRouteImport } from './routes/dir.$id_/file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirIdRouteRoute = DirIdRouteRouteImport.update({
  id: '/dir/$id',
  path: '/dir/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DirIdFileRoute = DirIdFileRouteImport.update({
  id: '/dir/$id_/file',
  path: '/dir/$id/file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dir/$id': typeof DirIdRouteRoute
  '/dir/$id/file': typeof DirIdFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dir/$id': typeof DirIdRouteRoute
  '/dir/$id/file': typeof DirIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dir/$id': typeof DirIdRouteRoute
  '/dir/$id_/file': typeof DirIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dir/$id' | '/dir/$id/file'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dir/$id' | '/dir/$id/file'
  id: '__root__' | '/' | '/dir/$id' | '/dir/$id_/file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirIdRouteRoute: typeof DirIdRouteRoute
  DirIdFileRoute: typeof DirIdFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dir/$id': {
      id: '/dir/$id'
      path: '/dir/$id'
      fullPath: '/dir/$id'
      preLoaderRoute: typeof DirIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dir/$id_/file': {
      id: '/dir/$id_/file'
      path: '/dir/$id/file'
      fullPath: '/dir/$id/file'
      preLoaderRoute: typeof DirIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirIdRouteRoute: DirIdRouteRoute,
  DirIdFileRoute: DirIdFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
